include:
  - ../db-granul8/compose.yaml

services:
  api-granul8:
    build: .
    container_name: api-granul8
    ports:
      - "${API_PORT}:${API_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT}/healthcheck" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 50s
    networks:
      - net-granul8
    depends_on:
      - db-granul8
networks:
  net-granul8:
    driver: bridge
