import { IAttributeTypeControllerCreateAttributeTypeOutputError } from './IAttributeTypeControllerCreateAttributeTypeOutputError';
import { IAttributeTypeControllerCreateAttributeTypeOutputSuccess } from './IAttributeTypeControllerCreateAttributeTypeOutputSuccess';

export type IAttributeTypeControllerCreateAttributeTypeOutput =
  | IAttributeTypeControllerCreateAttributeTypeOutputSuccess
  | IAttributeTypeControllerCreateAttributeTypeOutputError;
