import { IResourceAttributeControllerDeleteResourceAttributeOutputError } from './IResourceAttributeControllerDeleteResourceAttributeOutputError';
import { IResourceAttributeControllerDeleteResourceAttributeOutputSuccess } from './IResourceAttributeControllerDeleteResourceAttributeOutputSuccess';

export type IResourceAttributeControllerDeleteResourceAttributeOutput =
  | IResourceAttributeControllerDeleteResourceAttributeOutputSuccess
  | IResourceAttributeControllerDeleteResourceAttributeOutputError;
