import { IResourceAttributeControllerCreateResourceAttributeOutputError } from './IResourceAttributeControllerCreateResourceAttributeOutputError';
import { IResourceAttributeControllerCreateResourceAttributeOutputSuccess } from './IResourceAttributeControllerCreateResourceAttributeOutputSuccess';

export type IResourceAttributeControllerCreateResourceAttributeOutput =
  | IResourceAttributeControllerCreateResourceAttributeOutputSuccess
  | IResourceAttributeControllerCreateResourceAttributeOutputError;
