import { IResourceAttributeControllerUpdateResourceAttributeOutputError } from './IResourceAttributeControllerUpdateResourceAttributeOutputError';
import { IResourceAttributeControllerUpdateResourceAttributeOutputSuccess } from './IResourceAttributeControllerUpdateResourceAttributeOutputSuccess';

export type IResourceAttributeControllerUpdateResourceAttributeOutput =
  | IResourceAttributeControllerUpdateResourceAttributeOutputSuccess
  | IResourceAttributeControllerUpdateResourceAttributeOutputError;
