import { IResourceAttributeControllerReadResourceAttributeOutputError } from './IResourceAttributeControllerReadResourceAttributeOutputError';
import { IResourceAttributeControllerReadResourceAttributeOutputSuccess } from './IResourceAttributeControllerReadResourceAttributeOutputSuccess';

export type IResourceAttributeControllerReadResourceAttributeOutput =
  | IResourceAttributeControllerReadResourceAttributeOutputSuccess
  | IResourceAttributeControllerReadResourceAttributeOutputError;
