import { IUserAttributeControllerReadUserAttributeOutputError } from './IUserAttributeControllerReadUserAttributeOutputError';
import { IUserAttributeControllerReadUserAttributeOutputSuccess } from './IUserAttributeControllerReadUserAttributeOutputSuccess';

export type IUserAttributeControllerReadUserAttributeOutput =
  | IUserAttributeControllerReadUserAttributeOutputSuccess
  | IUserAttributeControllerReadUserAttributeOutputError;
