import { IUserAttributeControllerDeleteUserAttributeOutputError } from './IUserAttributeControllerDeleteUserAttributeOutputError';
import { IUserAttributeControllerDeleteUserAttributeOutputSuccess } from './IUserAttributeControllerDeleteUserAttributeOutputSuccess';

export type IUserAttributeControllerDeleteUserAttributeOutput =
  | IUserAttributeControllerDeleteUserAttributeOutputSuccess
  | IUserAttributeControllerDeleteUserAttributeOutputError;
